replicaCount: 1
image:
  repository: cashservice
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8883
clients:
  accountservice: "http://{{ .Release.Name }}-accountservice.{{ .Release.Namespace }}.svc.cluster.local:8881/api"
  blockerservice: "http://{{ .Release.Name }}-blockerservice.{{ .Release.Namespace }}.svc.cluster.local:8882/api"
keycloak:
  issuer: "http://{{ .Release.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bankapp"
kafka:
  url: "http://{{ .Release.Name }}-kafka.{{ .Release.Namespace }}.svc.cluster.local:9092"
zipkin:
  url: "http://{{ .Release.Name }}-zipkin:9411/api/v2/spans"