apiVersion: v1
kind: Service
metadata:
  name: {{ include "exchangegeneratorservice.fullname" . }}
  labels:
    {{- include "exchangegeneratorservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.ports.exchangegeneratorservice_port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "exchangegeneratorservice.selectorLabels" . | nindent 4 }}
