apiVersion: v1
kind: Service
metadata:
  name: {{ include "accountservice.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.ports.accountservice_port }}
      targetPort: {{ .Values.global.ports.accountservice_port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "accountservice.name" . }}

