apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailhog.fullname" . }}
spec:
  selector:
    app: {{ include "mailhog.name" . }}
  ports:
    - name: smtp
      port: {{ .Values.global.ports.mail_smtp_port }}
      targetPort: {{ .Values.global.ports.mail_smtp_port }}
    - name: http
      port: {{ .Values.global.ports.mail_http_port }}
      targetPort: {{ .Values.global.ports.mail_http_port }}

