apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cashservice.fullname" . }}-monitor
  labels:
    app: {{ include "cashservice.name" . }}
spec:
  jobLabel: cashservice
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 10s
  selector:
    matchLabels:
      app: {{ include "cashservice.name" . }}
  namespaceSelector:
    any: true