server:
  port: 8888

spring:
  application:
    name: frontservice
  security:
    oauth2:
      client:
        registration:
          account-service:
            client-id: frontservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope:
              - accountservice.post
              - accountservice.get
            provider: keycloak
          exchange-service:
            client-id: frontservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: exchangeservice.get
            provider: keycloak
          cash-service:
            client-id: frontservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: cashservice.post
            provider: keycloak
          transfer-service:
            client-id: frontservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: transferservice.post
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/banksapp/protocol/openid-connect/token
            issuer-uri: http://keycloak:8080/realms/banksapp

exchangeservice:
  url:
    rates: http://exchangeservice:8887/api/rates
    currencies: http://exchangeservice:8887/api/currencies

accountservice:
  url:
    users: http://accountservice:8881/api/users

transferservice:
  url:
    transfer: http://transferservice:8891/api/transfers/transfer

cashservice:
  url:
    operation: http://cashservice:8883/api/cash/operation
