server:
  port: 8888

spring:
  application:
    name: frontservice
  security:
    oauth2:
      client:
        registration:
          account-service:
            client-id: frontservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope:
              - accountservice.post
              - accountservice.get
            provider: keycloak
          exchange-service:
            client-id: frontservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: exchangeservice.get
            provider: keycloak
          cash-service:
            client-id: frontservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: cashservice.post
            provider: keycloak
          transfer-service:
            client-id: frontservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: transferservice.post
            provider: keycloak
        provider:
          keycloak:
            token-uri: ${ISSUER_URI}/protocol/openid-connect/token
            issuer-uri: ${ISSUER_URI}

exchangeservice:
  url: ${EXCHANGESERVICE_API}

accountservice:
  url: ${ACCOUNTSERVICE_API}

transferservice:
  url: ${TRANSFERSERVICE_API}

cashservice:
  url: ${CASHSERVICE_API}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh,metrics,env
  endpoint:
    health:
      show-details: always
      access: unrestricted