spring:
  application:
    name: transferservice

server:
  port: 8891

exchangeservice:
  url: http://localhost:8887/api/rates

accountservice:
  url: http://localhost:8881/api/accounts

blockerservice:
  url: http://localhost:8882/api/fraud-check

notificationservice:
  url: http://localhost:8890/api/notifications