server:
  port: 8891

spring:
  application:
    name: transferservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
      client:
        registration:
          account-service:
            client-id: transferservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: accountservice.post
            provider: keycloak
          blocker-service:
            client-id: transferservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: blockerservice.post
            provider: keycloak
          exchange-service:
            client-id: transferservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: exchangeservice.post
            provider: keycloak
        provider:
          keycloak:
            token-uri: ${ISSUER_URI}/protocol/openid-connect/token
            issuer-uri: ${ISSUER_URI}
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    topic:
      notifications: "notifications"
    properties:
      security.protocol: PLAINTEXT


exchangeservice:
  url: ${EXCHANGESERVICE_API}

accountservice:
  url: ${ACCOUNTSERVICE_API}

blockerservice:
  url: ${BLOCKERSERVICE_API}
