spring:
  application:

    name: transferservice
server:
  port: 8084

exchangeservice:
  url: http://exchangeservice/api/rates

accountservice:
  url: http://accountservice/api/accounts

blockerservice:
  url: http://localhost:8087/api/fraud-check

notificationservice:
  url: http://localhost:8089/api/notifications