replicaCount: 1
image:
  repository: exchangeservice
  tag: "1.0.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
database:
  url: "jdbc:postgresql://exchangedb-postgresql:5432/exchangedb"
  username: "login"
  password: "password"