apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notificationservice.fullname" . }}
  labels:
    app: {{ include "notificationservice.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "notificationservice.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "notificationservice.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ tpl .Values.database.url . | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ tpl .Values.database.username . | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ tpl .Values.database.password . | quote }}
            - name: MAILHOG
              value: {{ tpl .Values.clients.mailhog . | quote }}
            - name: MAIL_SMTP_PORT
              value: {{ tpl .Values.clients.port . | quote }}
            - name: ISSUER_URI
              value: {{ tpl .Values.keycloak.issuer . | quote }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}