services:

  notificationservice:
    container_name: notificationservice
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_SKIP_TESTS=true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notificationdb
      - SPRING_DATASOURCE_USERNAME=login
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 8890:8890
    depends_on:
      - notificationdb
    restart: unless-stopped

  notificationdb:
    container_name: notificationdb
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=notificationdb
      - POSTGRES_USER=login
      - POSTGRES_PASSWORD=password
    ports:
      - 5555:5432
    restart: unless-stopped