server:
  port: 8883

spring:
  application:
    name: cashservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/banksapp
      client:
        registration:
          account-service:
            client-id: cashservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: accountservice.post
            provider: keycloak
          blocker-service:
            client-id: cashservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: blockerservice.post
            provider: keycloak
          notification-service:
            client-id: cashservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: notificationservice.post
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/banksapp/protocol/openid-connect/token
            issuer-uri: http://keycloak:8080/realms/banksapp

accountservice:
  url: http://accountservice:8881/api/accounts

blockerservice:
  url: http://blockerservice:8882/api/fraud-check

notificationservice:
  url: http://notificationservice:8890/api/notifications