spring:
  application:
    name: cashservice

server:
  port: 8086

accountservice:
  url: http://accountservice/api/accounts

blockerservice:
  url: http://localhost:8087/api/fraud-check

notificationservice:
  url: http://notificationservice/api/notifications