spring:
  application:
    name: cashservice

server:
  port: 8883

accountservice:
  url: http://localhost:8881/api/accounts

blockerservice:
  url: http://localhost:8882/api/fraud-check

notificationservice:
  url: http://localhost:8890/api/notifications