server:
  port: 8883

spring:
  application:
    name: cashservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
      client:
        registration:
          account-service:
            client-id: cashservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: accountservice.post
            provider: keycloak
          blocker-service:
            client-id: cashservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: blockerservice.post
            provider: keycloak
          notification-service:
            client-id: cashservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: notificationservice.post
            provider: keycloak
        provider:
          keycloak:
            token-uri: ${ISSUER_URI}/protocol/openid-connect/token
            issuer-uri: ${ISSUER_URI}

accountservice:
  url: ${ACCOUNTSERVICE_API}

blockerservice:
  url: ${BLOCKERSERVICE_API}

notificationservice:
  url: ${NOTIFICATIONSERVICE_API}