apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchangeservice.fullname" . }}-config
  labels:
    {{- include "exchangeservice.labels" . | nindent 4 }}
data:
  ISSUER_URI: {{ tpl .Values.global.uri.issuer_uri . | quote }}
  DB_URL: {{ .Values.database.url | quote }}
  DB_USER: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}