apiVersion: v1
kind: Service
metadata:
  name: {{ include "exchangeservice.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.ports.exchangeservice_port }}
      targetPort: {{ .Values.global.ports.exchangeservice_port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "exchangeservice.name" . }}
