apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blockerservice.fullname" . }}-config
  labels:
    {{- include "blockerservice.labels" . | nindent 4 }}
data:
  ISSUER_URI: {{ tpl .Values.global.uri.issuer_uri . | quote }}
