apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockerservice.fullname" . }}
  labels:
    {{- include "blockerservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "blockerservice.selectorLabels" . | nindent 4 }}
