server:
  port: 8882

spring:
  application:
    name: blockerservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh,metrics,env,prometheus
  endpoint:
    health:
      show-details: always
      access: unrestricted
  tracing:
    enabled: true
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint:  ${ZIPKIN_URL}