server:
  port: 8882

spring:
  application:
    name: blockerservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh,metrics,env
  endpoint:
    health:
      show-details: always
      access: unrestricted