server:
  port: 8881

spring:
  application:
    name: accountservice
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    topic:
      notifications: "notifications"
    properties:
      security.protocol: PLAINTEXT
    template:
      observation-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh,metrics,env,prometheus
  endpoint:
    health:
      show-details: always
      access: unrestricted
  tracing:
    enabled: true
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}