server:
  port: 8886

spring:
  application:
    name: exchangegeneratorservice
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 0
    topic:
      rates: "rates"
    properties:
      security.protocol: PLAINTEXT
    template:
      observation-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh,metrics,env,prometheus
  endpoint:
    health:
      show-details: always
      access: unrestricted
  tracing:
    enabled: true
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
