server:
  port: 8886

spring:
  application:
    name: exchangegeneratorservice
  security:
    oauth2:
      client:
        registration:
          exchange-generator:
            client-id: exchangegeneratorservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: exchangeservice.post
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/banksapp/protocol/openid-connect/token
            issuer-uri: http://keycloak:8080/realms/banksapp

exchangeservice:
  url: http://exchangeservice:8885/api/generation
