replicaCount: 1
image:
  repository: ghcr.io/andrey1510/accountservice
  tag: 1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8881
database:
  url: "jdbc:postgresql://accountdb-postgresql:5432/accountdb"
  username: "login"
  password: "password"
clients:
  notificationservice: "http://{{ .Release.Name }}-notificationservice.{{ .Release.Namespace }}.svc.cluster.local:8890/api"
keycloak:
  issuer: "http://{{ .Release.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bankapp"
  token: "http://{{ .Release.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bankapp/protocol/openid-connect/certs"



