replicaCount: 1
image:
  repository: blockerservice
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8882
keycloak:
  issuer: "http://{{ .Release.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bankapp"
