pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = credentials('DOCKER_REGISTRY')
        GITHUB_USERNAME = credentials('GITHUB_USERNAME')
        IMAGE_TAG       = "${env.BUILD_NUMBER}"
    }

        stage('Deploy to TEST') {
            steps {
                dir('bankapp') {
                    sh 'find . -name "*.jar" -delete'
                    sh """
                    helm dependency update .
                    helm upgrade --install bankapp . \\
                      --namespace test --create-namespace
                    """
                }
            }
        }


    }

    post {
        always {
            echo 'Pipeline completed - cleaning up'
        }
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}