replicaCount: 1
image:
  repository: notificationservice
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8890
database:
  url: "jdbc:postgresql://{{ .Release.Name }}-notificationdb.{{ .Release.Namespace }}.svc.cluster.local:5432/notificationdb"
  username: "login"
  password: "password"
clients:
  mailhog: "{{ .Release.Name }}-mailhog.{{ .Release.Namespace }}.svc.cluster.local"
  mailport: "1025"
keycloak:
  issuer: "http://{{ .Release.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bankapp"
kafka:
  url: "http://{{ .Release.Name }}-kafka.{{ .Release.Namespace }}.svc.cluster.local:9092"
zipkin:
  url: "http://{{ .Release.Name }}-zipkin.{{ .Release.Namespace }}.svc.cluster.local:9411/api/v2/spans"