replicaCount: 1
image:
  repository: notificationservice
  tag: "1.0.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
database:
  url: "jdbc:postgresql://notificationdb-postgresql:5432/notificationdb"
  username: "login"
  password: "password"