server:
  port: 8887

spring:
  application:
    name: exchangeservice
  datasource:
    url: jdbc:postgresql://localhost:5556/exchangedb
    username: login
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
