services:

  exchangeservice:
    container_name: exchangeservice
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_SKIP_TESTS=true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/exchangedb
      - SPRING_DATASOURCE_USERNAME=login
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 8887:8887
    depends_on:
      - exchangedb
    restart: unless-stopped

  exchangedb:
    container_name: exchangedb
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=exchangedb
      - POSTGRES_USER=login
      - POSTGRES_PASSWORD=password
    ports:
      - 5558:5432
    restart: unless-stopped