replicaCount: 1
image:
  repository: exchangegeneratorservice
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8886
kafka:
  url: "http://{{ .Release.Name }}-kafka.{{ .Release.Namespace }}.svc.cluster.local:9092"
zipkin:
  url: "http://{{ .Release.Name }}-zipkin.{{ .Release.Namespace }}.svc.cluster.local:9411/api/v2/spans"