apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontservice.fullname" . }}-config
  labels:
    {{- include "frontservice.labels" . | nindent 4 }}
data:
  ISSUER_URI: {{ tpl .Values.global.uri.issuer_uri . | quote }}
  ACCOUNTSERVICE_API: {{ tpl .Values.global.uri.accountservice_api . | quote }}
  CASHSERVICE_API: {{ tpl .Values.global.uri.cashservice_api . | quote }}
  EXCHANGESERVICE_API: {{ tpl .Values.global.uri.exchangeservice_api . | quote }}
  TRANSFERSERVICE_API: {{ tpl .Values.global.uri.transferservice_api . | quote }}
