apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontservice.fullname" . }}
  labels:
    {{- include "frontservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "frontservice.name" . }}
  template:
    metadata:
      labels:
        app: frontservice
        app.kubernetes.io/instance: bankapp
        app.kubernetes.io/name: frontservice
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: EXCHANGESERVICE_API
              value: {{ tpl .Values.clients.exchangeservice . | quote }}
            - name: ACCOUNTSERVICE_API
              value: {{ tpl .Values.clients.accountservice . | quote }}
            - name: CASHSERVICE_API
              value: {{ tpl .Values.clients.cashservice . | quote }}
            - name: TRANSFERSERVICE_API
              value: {{ tpl .Values.clients.transferservice . | quote }}
            - name: ISSUER_URI
              value: {{ tpl .Values.keycloak.issuer . | quote }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 50
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 50
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}