apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontservice.fullname" . }}
  labels:
    {{- include "frontservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.ports.frontservice_port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "frontservice.selectorLabels" . | nindent 4 }}
