apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "frontservice.fullname" . }}-monitor
  labels:
    app: {{ include "frontservice.name" . }}
spec:
  jobLabel: frontservice
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 10s
  selector:
    matchLabels:
      app: {{ include "frontservice.name" . }}
  namespaceSelector:
    any: true