server:
  port: 8882

spring:
  application:
    name: blockerservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/banksapp

eureka:
  client:
    service-url:
      defaultZone: http://eurekaservice:8885/eureka/
  instance:
    hostname: blockerservice
    prefer-ip-address: true
