server:
  port: 8882

spring:
  application:
    name: blockerservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8892/realms/banksapp

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8885/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
