server:
  port: 8886

spring:
  application:
    name: exchangegeneratorservice
  security:
    oauth2:
      client:
        registration:
          exchange-generator:
            client-id: exchangegeneratorservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: exchangeservice.post
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/banksapp/protocol/openid-connect/token
            issuer-uri: http://keycloak:8080/realms/banksapp

eureka:
  client:
    service-url:
      defaultZone: http://eurekaservice:8885/eureka/
  instance:
    hostname: exchangegeneratorservice
    prefer-ip-address: true

exchangeservice:
    url: http://gatewayservice:8889/exchangeapp/api/generation
