server:
  port: 8889

spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: exchangeservice-api
          uri: lb://EXCHANGESERVICE
          predicates:
            - Path=/exchangeapp/api/**
          filters:
            - RewritePath=/exchangeapp(?<segment>/?.*), $\{segment}
        - id: cashservice-api
          uri: lb://CASHSERVICE
          predicates:
            - Path=/cashapp/api/**
          filters:
            - RewritePath=/cashapp(?<segment>/?.*), $\{segment}
        - id: transferservice-api
          uri: lb://TRANSFERSERVICE
          predicates:
            - Path=/transferapp/api/**
          filters:
            - RewritePath=/transferapp(?<segment>/?.*), $\{segment}
        - id: accountservice-api
          uri: lb://ACCOUNTSERVICE
          predicates:
            - Path=/accountapp/api/**
          filters:
            - RewritePath=/accountapp(?<segment>/?.*), $\{segment}
        - id: notificationservice-api
          uri: lb://NOTIFICATIONSERVICE
          predicates:
            - Path=/notificationapp/api/**
          filters:
            - RewritePath=/notificationapp(?<segment>/?.*), $\{segment}
        - id: blockerservice-api
          uri: lb://BLOCKERSERVICE
          predicates:
            - Path=/blockerapp/api/**
          filters:
            - RewritePath=/blockerapp(?<segment>/?.*), $\{segment}
        - id: frontservice-api
          uri: lb://FRONTSERVICE
          predicates:
            - Path=/frontapp/api/**
          filters:
            - RewritePath=/frontapp(?<segment>/?.*), $\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8885/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true