server:
  port: 8891

spring:
  application:
    name: transferservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/banksapp
      client:
        registration:
          account-service:
            client-id: transferservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: accountservice.post
            provider: keycloak
          blocker-service:
            client-id: transferservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: blockerservice.post
            provider: keycloak
          notification-service:
            client-id: transferservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: notificationservice.post
            provider: keycloak
          exchange-service:
            client-id: transferservice
            client-secret: XZxKQ8kk6Rrdbe7RnsfwtBTgHkwAqQjm
            authorization-grant-type: client_credentials
            scope: exchangeservice.post
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/banksapp/protocol/openid-connect/token
            issuer-uri: http://keycloak:8080/realms/banksapp

eureka:
  client:
    service-url:
      defaultZone: http://eurekaservice:8885/eureka/
  instance:
    hostname: transferservice
    prefer-ip-address: true

exchangeservice:
  url: http://gatewayservice:8889/exchangeapp/api/rates

accountservice:
  url: http://gatewayservice:8889/accountapp/api/accounts

blockerservice:
  url: http://gatewayservice:8889/blockerapp/api/fraud-check

notificationservice:
  url: http://gatewayservice:8889/notificationapp/api/notifications