server:
  port: 8884

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/
  profiles:
    active: native

management:
  endpoints:
    web:
      exposure:
        include: '*'