apiVersion: v1
kind: Service
metadata:
  name: {{ include "transferservice.fullname" . }}
  labels:
    {{- include "transferservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.ports.transferservice_port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "transferservice.selectorLabels" . | nindent 4 }}
