global:
  ports:
    accountservice_port: 8881
    blockerservice_port: 8882
    cashservice_port: 8883
    exchangegeneratorservice_port: 8886
    exchangeservice_port: 8887
    frontservice_port: 8888
    notificationservice_port: 8890
    transferservice_port: 8891
    mail_smtp_port: 1025
    mail_http_port: 8025
    keycloak_port: 8080
  uri:
    accountservice_api: "http://{{ .Release.Name }}-accountservice.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.ports.accountservice_port }}/api"
    blockerservice_api: "http://{{ .Release.Name }}-blockerservice.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.ports.blockerservice_port }}/api"
    cashservice_api: "http://{{ .Release.Name }}-cashservice.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.ports.cashservice_port }}/api"
    exchangeservice_api: "http://{{ .Release.Name }}-exchangeservice.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.ports.exchangeservice_port }}/api"
    frontservice_api: "http://{{ .Release.Name }}-exchangeservice.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.ports.frontservice_port }}/api"
    transferservice_api: "http://{{ .Release.Name }}-transferservice.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.ports.transferservice_port }}/api"
    notificationservice_api: "http://{{ .Release.Name }}-notificationservice.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.ports.notificationservice_port }}/api"
    issuer_uri: "http://{{ .Release.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.ports.keycloak_port }}/realms/bankapp"
    mailhog: "{{ .Release.Name }}-mailhog.{{ .Release.Namespace }}.svc.cluster.local"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: bankapp.local
      paths:
        - path: /api(/|$)(.*)
          pathType: Prefix

accountdb:
  enabled: true
  image:
    repository: bitnami/postgresql
    tag: 14
  auth:
    database: accountdb
    username: login
    password: password
  primary:
    service:
      nodePort: 5554

notificationdb:
  enabled: true
  image:
    repository: bitnami/postgresql
    tag: 14
  auth:
    database: notificationdb
    username: login
    password: password
  primary:
    service:
      nodePort: 5555

exchangedb:
  enabled: true
  image:
    repository: bitnami/postgresql
    tag: 14
  auth:
    database: exchangedb
    username: login
    password: password
  primary:
    service:
      nodePort: 5558

accountservice:
  image:
    repository: accountservice
    tag: "1.0.0"

blockerservice:
  image:
    repository: blockerservice
    tag: "1.0.0"

cashservice:
  image:
    repository: cashservice
    tag: "1.0.0"

exchangeservice:
  image:
    repository: exchangeservice
    tag: "1.0.0"

exchangegeneratorservice:
  image:
    repository: exchangegeneratorservice
    tag: "1.0.0"

frontservice:
  image:
    repository: frontservice
    tag: "1.0.0"

notificationservice:
  image:
    repository: notificationservice
    tag: "1.0.0"

transferservice:
  image:
    repository: transferservice
    tag: "1.0.0"


