accountdb:
  enabled: true
  image:
    repository: bitnami/postgresql
    tag: 14
  auth:
    database: accountdb
    username: login
    password: password
  primary:
    service:
      nodePort: 5554
    persistence:
      storageClass: "hostpath"
      size: 1Gi

notificationdb:
  enabled: true
  image:
    repository: bitnami/postgresql
    tag: 14
  auth:
    database: notificationdb
    username: login
    password: password
  primary:
    service:
      nodePort: 5555
    persistence:
      storageClass: "hostpath"
      size: 1Gi

exchangedb:
  enabled: true
  image:
    repository: bitnami/postgresql
    tag: 14
  auth:
    database: exchangedb
    username: login
    password: password
  primary:
    service:
      nodePort: 5558
    persistence:
      storageClass: "hostpath"
      size: 1Gi

kafka:
  enabled: true
  clusterId: "bankapp-kafka-cluster"
  service:
    enabled: true
    type: ClusterIP
    port: 9991
    name: "bankapp-kafka-broker"
  broker:
    replicaCount: 1
    persistence:
      size: 1Gi
  kraft:
    enabled: true
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT